# question 1

In [18]:
import numpy as np
a=np.matrix('1 34 5 2;5 2 6 7;2 6 89 0')
print(a.shape)

(3, 4)


# question 2

In [19]:
import numpy as np
a=np.matrix('1 2 4;1 4 65')
b=np.matrix('13 4 3 56;21 4 45 32')
c=np.matrix.transpose(a)
print(c*b)

[[  34    8   48   88]
 [ 110   24  186  240]
 [1417  276 2937 2304]]


# question 3

In [20]:
import numpy as np
a=np.matrix('1 43 2;5 21 45;6 2 5')
print(np.linalg.det(a))

10318.00000000001


# question 4

In [21]:
import numpy as np
a=np.matrix('1 4 21;5 3 6;2 2 6')
b=np.linalg.inv(a)
print(b)


[[ 0.33333333  1.         -2.16666667]
 [-1.         -2.          5.5       ]
 [ 0.22222222  0.33333333 -0.94444444]]
